import {SCENES,findHit,charm,TYPES} from './challenge.js?v=85';
const $=id=>document.getElementById(id),image=new Image(),canvas=$('scene'),ctx=canvas.getContext('2d'),KEY='little-finds-challenge-v2';
let saved={},index=0,found=new Set(),loaded=false,zoom=1,tx=0,ty=0,base=1,cw=1,ch=1,dpr=1,hintId=null,hintTimer,feedbackTimer,selected=null,sound=false,audio;
try{const value=JSON.parse(localStorage.getItem(KEY)||'{}');if(value&&typeof value==='object'&&!Array.isArray(value))saved=value;}catch{}
const views=new Map();
const scene=()=>SCENES[index];
function known(i){const valid=new Set(SCENES[i].items.map(t=>t[0]));return new Set((Array.isArray(saved[SCENES[i].id])?saved[SCENES[i].id]:[]).filter(id=>valid.has(id)));}
function persist(){saved[scene().id]=[...found];try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{message('Progress cannot be saved in this browser.');}}
function message(text){clearTimeout(feedbackTimer);$('feedback').textContent=text;feedbackTimer=setTimeout(()=>$('feedback').textContent='',2200);}
function tone(){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();for(const [i,f] of [523,659,784].entries()){const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=f;const t=audio.currentTime+i*.07;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.035,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.start(t);o.stop(t+.23);}}catch{}}
function thumbnail(c,t){const g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.fillStyle='#f1e6cf';g.fillRect(0,0,c.width,c.height);charm(g,t[6],c.width/2,c.height/2,Math.min(c.width,c.height)*.30);}
function home(){ if(!$('play').hidden)views.set(index,{zoom,tx,ty}); $('home').hidden=false;$('play').hidden=true;hintId=null;clearTimeout(hintTimer);$('scene-list').replaceChildren();SCENES.forEach((s,i)=>{const b=document.createElement('button');b.className='scene-card';b.setAttribute('aria-label','Play '+s.title);const c=document.createElement('canvas');c.width=245;c.height=481;c.getContext('2d').drawImage(image,s.sx,s.sy,s.w,s.h,0,0,245,481);const text=document.createElement('span');text.className='caption';const h=document.createElement('strong');h.textContent=s.title;const p=document.createElement('small');p.textContent=s.subtitle;const n=document.createElement('small');n.textContent=`${known(i).size} / ${s.items.length} discovered`;text.append(h,p,n);b.append(c,text);b.onclick=()=>open(i);$('scene-list').append(b);});}
function open(i){index=i;found=known(i);$('home').hidden=true;$('play').hidden=false;$('title').textContent=scene().title;hintId=null;clearTimeout(hintTimer);$('feedback').textContent='';renderTray();resize(true);if(views.has(i)){({zoom,tx,ty}=views.get(i));clamp();draw();}if(found.size===scene().items.length)complete();}
function renderTray(){const scroll=$('targets').scrollLeft;canvas.dataset.scene=scene().id;canvas.dataset.found=String(found.size);$('progress').textContent=`${found.size} / 100 hidden charms`;$('remaining').textContent=`${100-found.size} left`;$('targets').replaceChildren();TYPES.forEach((name,type)=>{const group=scene().items.filter(t=>t[6]===type),remaining=group.filter(t=>!found.has(t[0])),t=remaining[0]||group[0],b=document.createElement('button');b.className=remaining.length?'':'found';b.setAttribute('aria-label',`${name}: ${10-remaining.length} of 10 found`);const c=document.createElement('canvas');c.width=100;c.height=86;thumbnail(c,t);const label=document.createElement('span');label.textContent=`${name} ${10-remaining.length}/10`;b.append(c,label);b.onclick=()=>{selected=t;thumbnail($('item-picture'),t);$('item-name').textContent=name;$('item-hint').hidden=!remaining.length;$('item-dialog').showModal();};$('targets').append(b);});$('targets').scrollLeft=scroll;}
function clamp(){const w=scene().w*base*zoom,h=scene().h*base*zoom;tx=w<=cw?(cw-w)/2:Math.max(cw-w,Math.min(0,tx));ty=h<=ch?(ch-h)/2:Math.max(ch-h,Math.min(0,ty));}
function resize(reset=false){if($('play').hidden)return;const worldX=(cw/2-tx)/(base*zoom),worldY=(ch/2-ty)/(base*zoom);const r=$('board').getBoundingClientRect();cw=r.width;ch=r.height;dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(cw*dpr);canvas.height=Math.round(ch*dpr);base=Math.min(cw/scene().w,ch/scene().h);if(reset){zoom=Math.max(1,cw/(scene().w*base));tx=0;ty=0;}else{tx=cw/2-worldX*base*zoom;ty=ch/2-worldY*base*zoom;}clamp();draw();}
let drawPending=false;function draw(){if(typeof requestAnimationFrame==='undefined'){paint();return;}if(drawPending)return;drawPending=true;requestAnimationFrame(()=>{drawPending=false;paint();});}
function paint(){if(!loaded||$('play').hidden)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#eadcc7';ctx.fillRect(0,0,cw,ch);ctx.save();ctx.translate(tx,ty);ctx.scale(base*zoom,base*zoom);const s=scene();ctx.drawImage(image,s.sx,s.sy,s.w,s.h,0,0,s.w,s.h);for(const t of s.items)if(!found.has(t[0])){ctx.save();ctx.translate(t[2],t[3]);ctx.rotate(t[8]);ctx.globalAlpha=.88;charm(ctx,t[6],0,0,t[7]);ctx.restore();}for(const t of s.items)if(found.has(t[0])){ctx.beginPath();ctx.ellipse(t[2],t[3],t[4]+4,t[5]+4,0,0,Math.PI*2);ctx.strokeStyle='#ffffff';ctx.lineWidth=3/(base*zoom);ctx.stroke();ctx.strokeStyle='#477351';ctx.lineWidth=1.5/(base*zoom);ctx.stroke();}if(hintId){const t=s.items.find(t=>t[0]===hintId);ctx.beginPath();ctx.arc(t[2],t[3],Math.max(t[4],t[5])+22,0,Math.PI*2);ctx.lineWidth=5/(base*zoom);ctx.strokeStyle='#ffef8c';ctx.shadowColor='#70481b';ctx.shadowBlur=8;ctx.stroke();}ctx.restore();$('minus').disabled=zoom<=1;$('plus').disabled=zoom>=8;$('zoom-range').value=zoom;$('zoom-label').textContent=zoom.toFixed(1)+'×';const m=$('map').getContext('2d');m.clearRect(0,0,60,100);m.drawImage(image,s.sx,s.sy,s.w,s.h,0,0,60,100);m.fillStyle='#ffffff40';m.fillRect(0,0,60,100);m.strokeStyle='#a64126';m.lineWidth=2;m.strokeRect(-tx/(base*zoom)/s.w*60,-ty/(base*zoom)/s.h*100,cw/(base*zoom)/s.w*60,ch/(base*zoom)/s.h*100);}
function zoomAt(next,x=cw/2,y=ch/2){next=Math.max(1,Math.min(8,next));const ratio=next/zoom;tx=x-(x-tx)*ratio;ty=y-(y-ty)*ratio;zoom=next;clamp();draw();}
function hint(t=scene().items.find(t=>!found.has(t[0]))){if(!t){complete();return;}hintId=t[0];zoom=Math.max(zoom,1.8);tx=cw/2-t[2]*base*zoom;ty=ch/2-t[3]*base*zoom;clamp();draw();message('Look around the golden circle');clearTimeout(hintTimer);hintTimer=setTimeout(()=>{hintId=null;draw();},3500);}
function tap(x,y){const t=findHit(scene().items,found,(x-tx)/(base*zoom),(y-ty)/(base*zoom),Math.min(3,3/(base*zoom)));if(!t)return;found.add(t[0]);hintId=null;persist();renderTray();draw();tone();message('Found: '+t[1]+' ♥');if(found.size===scene().items.length)complete();}
function complete(){$('next').textContent=index===SCENES.length-1?'Back to all scenes':'Explore the next scene';if(!$('complete').open)$('complete').showModal();}
const pointers=new Map();let pinch=null;
function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();const p=pos(e);pointers.set(e.pointerId,{...p,sx:p.x,sy:p.y,moved:false});try{canvas.setPointerCapture(e.pointerId);}catch{}if(pointers.size>=2){for(const p of pointers.values())p.moved=true;const [a,b]=[...pointers.values()];pinch={d:Math.hypot(a.x-b.x,a.y-b.y),x:(a.x+b.x)/2,y:(a.y+b.y)/2};}});
canvas.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(!p)return;e.preventDefault();const q=pos(e),dx=q.x-p.x,dy=q.y-p.y;if(Math.hypot(q.x-p.sx,q.y-p.sy)>8)p.moved=true;p.x=q.x;p.y=q.y;if(pointers.size>=2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y),cx=(a.x+b.x)/2,cy=(a.y+b.y)/2;if(pinch&&pinch.d){tx+=cx-pinch.x;ty+=cy-pinch.y;zoomAt(zoom*d/pinch.d,cx,cy);}pinch={d,x:cx,y:cy};}else{tx+=dx;ty+=dy;clamp();draw();}});
function release(e){const p=pointers.get(e.pointerId);if(!p)return;pointers.delete(e.pointerId);if(e.type==='pointerup'&&!p.moved)tap(p.x,p.y);pinch=null;}
for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,release);
canvas.addEventListener('wheel',e=>{e.preventDefault();const p=pos(e);zoomAt(zoom*(e.deltaY<0?1.15:.87),p.x,p.y);},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
$('plus').onclick=()=>zoomAt(zoom*1.4);$('minus').onclick=()=>zoomAt(zoom/1.4);$('fit').onclick=()=>{zoom=1;clamp();draw();};$('zoom-range').oninput=e=>zoomAt(Number(e.target.value));$('map').onclick=e=>{const r=$('map').getBoundingClientRect();tx=cw/2-(e.clientX-r.left)/r.width*scene().w*base*zoom;ty=ch/2-(e.clientY-r.top)/r.height*scene().h*base*zoom;clamp();draw();};canvas.addEventListener('dblclick',e=>{e.preventDefault();const p=pos(e);zoomAt(zoom<3?3:zoom<6?6:1,p.x,p.y);});$('hint').onclick=()=>hint();$('back').onclick=home;$('close-item').onclick=()=>$('item-dialog').close();$('item-hint').onclick=()=>{$('item-dialog').close();hint(selected);};$('next').onclick=()=>{$('complete').close();if(index<2)open(index+1);else home();};$('all-scenes').onclick=()=>{$('complete').close();home();};$('again').onclick=()=>{$('complete').close();found.clear();persist();open(index);};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Turn sound off':'Turn sound on');if(sound)tone();};
addEventListener('resize',()=>resize());addEventListener('blur',()=>{pointers.clear();pinch=null;});
image.onload=()=>{loaded=true;$('loading').hidden=true;home();};image.onerror=()=>{$('scene-list').textContent='The artwork could not load. Please reload when connected.';};image.src='scenes-v1.png';
