import {SCENES,findHit} from './scenes.js?v=84';
const $=id=>document.getElementById(id),image=new Image(),canvas=$('scene'),ctx=canvas.getContext('2d'),KEY='little-finds-progress-v1';
let saved={},index=0,found=new Set(),loaded=false,zoom=1,tx=0,ty=0,base=1,cw=1,ch=1,dpr=1,hintId=null,hintTimer,feedbackTimer,selected=null,sound=false,audio;
try{const value=JSON.parse(localStorage.getItem(KEY)||'{}');if(value&&typeof value==='object'&&!Array.isArray(value))saved=value;}catch{}
const scene=()=>SCENES[index];
function known(i){const valid=new Set(SCENES[i].items.map(t=>t[0]));return new Set((Array.isArray(saved[SCENES[i].id])?saved[SCENES[i].id]:[]).filter(id=>valid.has(id)));}
function persist(){saved[scene().id]=[...found];try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{message('Progress cannot be saved in this browser.');}}
function message(text){clearTimeout(feedbackTimer);$('feedback').textContent=text;feedbackTimer=setTimeout(()=>$('feedback').textContent='',2200);}
function tone(){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();for(const [i,f] of [523,659,784].entries()){const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=f;const t=audio.currentTime+i*.07;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.035,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.start(t);o.stop(t+.23);}}catch{}}
function thumbnail(c,t,i=index){const s=SCENES[i],g=c.getContext('2d'),size=Math.max(t[4]*2.7,t[5]*2.7,48),left=Math.max(0,Math.min(s.w-size,t[2]-size/2)),top=Math.max(0,Math.min(s.h-size,t[3]-size/2));g.drawImage(image,s.sx+left,s.sy+top,size,size,0,0,c.width,c.height);}
function home(){ $('home').hidden=false;$('play').hidden=true;hintId=null;clearTimeout(hintTimer);$('scene-list').replaceChildren();SCENES.forEach((s,i)=>{const b=document.createElement('button');b.className='scene-card';b.setAttribute('aria-label','Play '+s.title);const c=document.createElement('canvas');c.width=245;c.height=481;c.getContext('2d').drawImage(image,s.sx,s.sy,s.w,s.h,0,0,245,481);const text=document.createElement('span');text.className='caption';const h=document.createElement('strong');h.textContent=s.title;const p=document.createElement('small');p.textContent=s.subtitle;const n=document.createElement('small');n.textContent=`${known(i).size} / ${s.items.length} discovered`;text.append(h,p,n);b.append(c,text);b.onclick=()=>open(i);$('scene-list').append(b);});}
function open(i){index=i;found=known(i);$('home').hidden=true;$('play').hidden=false;$('title').textContent=scene().title;hintId=null;clearTimeout(hintTimer);$('feedback').textContent='';renderTray();resize(true);if(found.size===scene().items.length)complete();}
function renderTray(){canvas.dataset.scene=scene().id;canvas.dataset.found=String(found.size);$('progress').textContent=`${found.size} of ${scene().items.length} little things found`;$('remaining').textContent=`${scene().items.length-found.size} left`;$('targets').replaceChildren();scene().items.forEach(t=>{const b=document.createElement('button');b.className=found.has(t[0])?'found':'';b.setAttribute('aria-label',t[1]+(found.has(t[0])?' — found':''));b.setAttribute('aria-pressed',String(found.has(t[0])));const c=document.createElement('canvas');c.width=100;c.height=86;thumbnail(c,t);const label=document.createElement('span');label.textContent=t[1];b.append(c,label);b.onclick=()=>{selected=t;thumbnail($('item-picture'),t);$('item-name').textContent=t[1];$('item-hint').hidden=found.has(t[0]);$('item-dialog').showModal();};$('targets').append(b);});}
function clamp(){const w=scene().w*base*zoom,h=scene().h*base*zoom;tx=w<=cw?(cw-w)/2:Math.max(cw-w,Math.min(0,tx));ty=h<=ch?(ch-h)/2:Math.max(ch-h,Math.min(0,ty));}
function resize(reset=false){if($('play').hidden)return;const r=$('board').getBoundingClientRect();cw=r.width;ch=r.height;dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(cw*dpr);canvas.height=Math.round(ch*dpr);base=Math.min(cw/scene().w,ch/scene().h);if(reset)zoom=1;clamp();draw();}
function draw(){if(!loaded||$('play').hidden)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#eadcc7';ctx.fillRect(0,0,cw,ch);ctx.save();ctx.translate(tx,ty);ctx.scale(base*zoom,base*zoom);const s=scene();ctx.drawImage(image,s.sx,s.sy,s.w,s.h,0,0,s.w,s.h);for(const t of s.items)if(found.has(t[0])){ctx.beginPath();ctx.ellipse(t[2],t[3],t[4]+4,t[5]+4,0,0,Math.PI*2);ctx.strokeStyle='#ffffff';ctx.lineWidth=3/(base*zoom);ctx.stroke();ctx.strokeStyle='#477351';ctx.lineWidth=1.5/(base*zoom);ctx.stroke();}if(hintId){const t=s.items.find(t=>t[0]===hintId);ctx.beginPath();ctx.arc(t[2],t[3],Math.max(t[4],t[5])+22,0,Math.PI*2);ctx.lineWidth=5/(base*zoom);ctx.strokeStyle='#ffef8c';ctx.shadowColor='#70481b';ctx.shadowBlur=8;ctx.stroke();}ctx.restore();$('minus').disabled=zoom<=1;$('plus').disabled=zoom>=4;}
function zoomAt(next,x=cw/2,y=ch/2){next=Math.max(1,Math.min(4,next));const ratio=next/zoom;tx=x-(x-tx)*ratio;ty=y-(y-ty)*ratio;zoom=next;clamp();draw();}
function hint(t=scene().items.find(t=>!found.has(t[0]))){if(!t){complete();return;}hintId=t[0];zoom=Math.max(zoom,1.8);tx=cw/2-t[2]*base*zoom;ty=ch/2-t[3]*base*zoom;clamp();draw();message('Look around the golden circle');clearTimeout(hintTimer);hintTimer=setTimeout(()=>{hintId=null;draw();},3500);}
function tap(x,y){const t=findHit(scene().items,found,(x-tx)/(base*zoom),(y-ty)/(base*zoom),Math.min(9,7/(base*zoom)));if(!t)return;found.add(t[0]);hintId=null;persist();renderTray();draw();tone();message('Found: '+t[1]+' ♥');if(found.size===scene().items.length)complete();}
function complete(){$('next').textContent=index===SCENES.length-1?'Back to all scenes':'Explore the next scene';if(!$('complete').open)$('complete').showModal();}
const pointers=new Map();let pinch=null;
function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();const p=pos(e);pointers.set(e.pointerId,{...p,sx:p.x,sy:p.y,moved:false});try{canvas.setPointerCapture(e.pointerId);}catch{}if(pointers.size>=2){for(const p of pointers.values())p.moved=true;pinch=null;}});
canvas.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(!p)return;e.preventDefault();const q=pos(e),dx=q.x-p.x,dy=q.y-p.y;if(Math.hypot(q.x-p.sx,q.y-p.sy)>8)p.moved=true;p.x=q.x;p.y=q.y;if(pointers.size>=2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y),cx=(a.x+b.x)/2,cy=(a.y+b.y)/2;if(pinch&&pinch.d){tx+=cx-pinch.x;ty+=cy-pinch.y;zoomAt(zoom*d/pinch.d,cx,cy);}pinch={d,x:cx,y:cy};}else{tx+=dx;ty+=dy;clamp();draw();}});
function release(e){const p=pointers.get(e.pointerId);if(!p)return;pointers.delete(e.pointerId);if(e.type==='pointerup'&&!p.moved)tap(p.x,p.y);pinch=null;}
for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,release);
canvas.addEventListener('wheel',e=>{e.preventDefault();const p=pos(e);zoomAt(zoom*(e.deltaY<0?1.15:.87),p.x,p.y);},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
$('plus').onclick=()=>zoomAt(zoom*1.4);$('minus').onclick=()=>zoomAt(zoom/1.4);$('fit').onclick=()=>resize(true);$('hint').onclick=()=>hint();$('back').onclick=home;$('close-item').onclick=()=>$('item-dialog').close();$('item-hint').onclick=()=>{$('item-dialog').close();hint(selected);};$('next').onclick=()=>{$('complete').close();if(index<2)open(index+1);else home();};$('all-scenes').onclick=()=>{$('complete').close();home();};$('again').onclick=()=>{$('complete').close();found.clear();persist();open(index);};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Turn sound off':'Turn sound on');if(sound)tone();};
addEventListener('resize',()=>resize());addEventListener('blur',()=>{pointers.clear();pinch=null;});
image.onload=()=>{loaded=true;$('loading').hidden=true;home();};image.onerror=()=>{$('scene-list').textContent='The artwork could not load. Please reload when connected.';};image.src='scenes-v1.png';
