const fs=require('fs'),assert=require('assert/strict');const {chromium}=require('C:/Users/garet/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/Codex 2/projects/NES-Wide64-HPBP169',edition=JSON.parse(fs.readFileSync(root+'/dbz-wide64-v9-edition.json'));
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('error',e.message)});
page.on('console',m=>{if(m.text().startsWith('battle179'))console.log(m.text());});
await page.goto((process.env.BASE||'http://127.0.0.1:8176')+'/dbz-wide64-v9-play.html');
await page.evaluate(async({bytes,id})=>{await new Promise((ok,no)=>{const q=indexedDB.open('nes-dream-library-v1',2);q.onsuccess=()=>{const d=q.result,t=d.transaction('states','readwrite');t.objectStore('states').put({key:id+':1',gameId:id,slot:1,bytes:new Uint8Array(bytes).buffer,updated:Date.now()});t.oncomplete=()=>{d.close();ok();};t.onerror=()=>no(t.error);};q.onerror=()=>no(q.error);});},{bytes:[...fs.readFileSync(process.env.FIXTURE||__dirname+'/v9-400.state')],id:edition.romId});
await page.frameLocator('iframe').getByRole('button',{name:'Play game',exact:true}).click({timeout:60000});const f=page.frames().find(f=>f.url().includes('/player-wide64-v9.html'));await f.waitForFunction(()=>window.dreamArtwork?.metrics?.frames>2);
await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByRole('button',{name:/Slot 1/}).click();await page.waitForTimeout(600);
await page.screenshot({path:__dirname+'/ui-loaded.png'});

await f.evaluate(()=>{const g=EJS_emulator.gameManager;window.qaRead179=()=>{const b=g.getState(),r=DreamWide64.chunk(b,'RAM',2048),w=DreamWide64.chunk(b,'WRM',8192);return {phase:[...b.slice(r+46,r+50)],kills:[b[w+0x13bb],b[w+0x13bc]],forms:b[w+0x15ae],queue:b[w+0x13be],loaded:b[w+0x139a]+256*b[w+0x139b],pending:b[w+0x1396]+256*b[w+0x1397],frame:g.getFrameNum(),banner:DreamWide64Awakening.inspect()};};document.querySelector('[data-lock-code="8"]').click();});

const events=[],frames=[];let previous='',nextShot=0;const start=Date.now();
while(Date.now()-start<160000){await page.waitForTimeout(100);const v=await f.evaluate(()=>{const v=qaRead179();const a=document.querySelector('[data-lock-code="8"]');if(!v.banner.busy&&a.getAttribute('aria-pressed')!=='true')a.click();const d=document.querySelector('#dbz-skills');if(!v.banner.busy&&d&&!d.hidden){const skill=d.querySelector('[data-skill="34"]');if(skill&&!skill.disabled)skill.click();else{const folder=[...d.querySelectorAll('button')].find(b=>b.textContent.includes('Frieza')&&!b.textContent.includes('soldiers'));if(folder)folder.click();}}return v;});const key=JSON.stringify([v.phase[0],v.kills,v.forms,v.queue,v.loaded,v.pending]);if(key!==previous){events.push(v);console.log('event',JSON.stringify(v));previous=key;}if(Date.now()>nextShot&&!v.banner.busy){const png=await f.evaluate(()=>{if(!DreamFrameSource.pixels?.length)return null;const c=document.createElement('canvas');c.width=256;c.height=240;c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(DreamFrameSource.pixels),256,240),0,0);return c.toDataURL();});const i=frames.length;if(png){fs.writeFileSync(__dirname+'/native-battle-'+i+'.png',Buffer.from(png.split(',')[1],'base64'));frames.push({i,...v});}nextShot=Date.now()+1500;}if(v.phase[0]!==1)break;}
DreamResult=events.at(-1);await f.evaluate(()=>{DreamTouch.releaseAll();EJS_emulator.pause();});await page.screenshot({path:__dirname+'/full400-final.png'});fs.writeFileSync(__dirname+'/full400-final.state',Buffer.from(await f.evaluate(()=>[...EJS_emulator.gameManager.getState()])));fs.writeFileSync(__dirname+'/full400-result.json',JSON.stringify({events,frames,errors},null,2));assert.equal(DreamResult.loaded,400);assert.equal(DreamResult.pending,0);assert.notEqual(DreamResult.phase[0],1);assert.equal(errors.length,0);await browser.close();})();
