from pathlib import Path
r=Path('D:/Codex 2/projects/NES-Wide64-HPBP169')
def edit(name,changes):
 p=r/name;s=p.read_text(encoding='utf8')
 for old,new in changes:
  assert old in s,(name,old[:90]);s=s.replace(old,new)
 p.write_text(s,encoding='utf8')
edit('dbz-wide64-v9-forms.js',[("function prepare(input,slot,on){const before=inspect(input,slot),out=before.b.slice();out[before.forms]=on?out[before.forms]|before.bit:out[before.forms]&~before.bit;", "function prepare(input,slot,on){const before=inspect(input,slot),out=before.b.slice(),used=before.w+0x13bd;if(on&&(out[before.forms]&before.bit))throw Error('This fighter is already transformed.');if(on&&(out[used]&before.bit))throw Error('Transform can be used only once per fight.');out[before.forms]=on?out[before.forms]|before.bit:out[before.forms]&~(before.bit|before.bit*4);if(on)out[used]|=before.bit;else out[before.w+0x13be]&=~before.bit;")])
edit('dbz-wide64-v9-skills.js',[("const el=button(moveLabel(id)","if(id>=35){const form=window.DreamWide64Forms.inspect(saved.state,slot),on=!!(saved.state[form.forms]&form.bit),used=!!(saved.state[form.w+0x13bd]&form.bit);if(id===35&&(on||used)||id===36&&!on)continue;}const el=button(moveLabel(id)")])
edit('dbz-wide64-v9-panel.js',[("multiplied=superSaiyan?base*100n:base", "stageII=superSaiyan&&!!(forms&(id===1?4:8)),multiplier=stageII?10000n:superSaiyan?100n:1n,multiplied=base*multiplier"),("combatBp:combat.toString(),superSaiyan}","combatBp:combat.toString(),superSaiyan,stageII,multiplier:multiplier.toString()}"),("${row.superSaiyan?' · Super Saiyan':''}","${row.stageII?' · Super Saiyan II':row.superSaiyan?' · Super Saiyan I':''}"),("${row.superSaiyan?' (100×)':''}","${row.superSaiyan?` (${group(row.multiplier)}×)`:''}"),("There is no BP, story or NG+ unlock.","Transform can be used once per fight. Each fighter automatically reaches Super Saiyan II after 10 personal defeats while transformed; II multiplies stage I BP by 100.")])
edit('dbz-wide64-v9-enemy-info.js',[("if(role===0&&((actor===1&&forms&1)||(actor===3&&forms&2)))bp=bp*100n>((1n<<64n)-1n)?((1n<<64n)-1n):bp*100n;", "if(role===0&&((actor===1&&forms&1)||(actor===3&&forms&2))){const factor=forms&(actor===1?4:8)?10000n:100n;bp=bp*factor>((1n<<64n)-1n)?((1n<<64n)-1n):bp*factor;}"),("if(superSaiyan)bp=bp*100n>max?max:bp*100n;", "const stageII=superSaiyan&&!!(forms&(h.actor===1?4:8)),factor=stageII?10000n:100n;if(superSaiyan)bp=bp*factor>max?max:bp*factor;"),("baseBp,superSaiyan}","baseBp,superSaiyan,stageII}"),("ctx.fillText('SSJ ×100',", "ctx.fillText(row.stageII?'SSJ II ×10,000':'SSJ I ×100',")])
