const fs=require('fs'),assert=require('assert/strict');const{chromium}=require('C:/Users/garet/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const q=__dirname,r='D:/Codex 2/projects/NES-Wide64-HPBP169',ed=JSON.parse(fs.readFileSync(r+'/dbz-wide64-v17-edition.json')),sizes=(process.env.SIZES||'5,20,100,400').split(',').map(Number);
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
for(const n of sizes){const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,...(process.env.VIDEO?{recordVideo:{dir:q+'/video',size:{width:390,height:844}}}:{})}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let result;
try{
 console.log('START',n);await page.addInitScript(id=>localStorage.setItem('nes-dream:dbz-crazy-cards:'+id,JSON.stringify({cards:[256,255,64,16,8].map(defense=>({attack:256,defense,attribute:1,locked:true}))})),ed.romId);await page.goto((process.env.BASE||'http://127.0.0.1:8176')+'/dbz-wide64-v17-play.html');console.log('GOTO',n);await page.locator('#wide64-v17-preview-notice').waitFor();console.log('HOST',n);
 await page.evaluate(async({bytes,id})=>new Promise((ok,no)=>{const request=indexedDB.open('nes-dream-library-v1',2);request.onsuccess=()=>{const db=request.result,t=db.transaction('states','readwrite');t.objectStore('states').put({key:id+':1',gameId:id,slot:1,bytes:new Uint8Array(bytes).buffer,updated:Date.now()});t.oncomplete=()=>{db.close();ok()};t.onerror=no;};}),{bytes:[...fs.readFileSync(q+'/v17-'+n+(process.env.FLAVOR?'-'+process.env.FLAVOR:process.env.MIXED?'-mixed':'')+'.state')],id:ed.romId});
 console.log('SEEDED',n);await page.frameLocator('iframe').getByRole('button',{name:'Play game',exact:true}).click({timeout:60000});const f=page.frames().find(f=>f.url().includes('/player-wide64-v17.html'));await f.waitForFunction(()=>window.dreamArtwork?.metrics.frames>2,{},{timeout:60000});console.log('STARTED',n);await page.evaluate(()=>document.querySelector('iframe').contentWindow.postMessage({channel:'nes-dream',type:'speed',value:4},location.origin));await f.evaluate(()=>DreamTouch.settings({a:4,b:6}));await page.waitForTimeout(300);await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByRole('button',{name:/Slot 1/}).click();await page.waitForTimeout(300);
 await f.evaluate(()=>{window.qaDraws=[];window.qaFrames={};window.qaPauses=[];const pause=EJS_emulator.pause;EJS_emulator.pause=function(...args){qaPauses.push({at:performance.now(),stack:Error().stack});return pause.apply(this,args);};const draw=DreamGroupBlastVisual.draw;DreamGroupBlastVisual.draw=function(ctx,w,h,scene){draw(ctx,w,h,scene);const d=DreamGroupBlastVisual.inspect().lastDraw;qaDraws.push({time:performance.now(),...d,before:scene.remainingBefore,dead:scene.enemies.filter(e=>e.beforeHp>0&&e.afterHp===0).length,size:scene.enemies.length,types:scene.enemies.map(e=>e.type)});if(!scene.waiting&&scene.groupIndex<2){const key=scene.groupIndex+'-'+d.stage;if(!qaFrames[key])qaFrames[key]=ctx.canvas.toDataURL();}};
  window.qaRead=()=>{const b=EJS_emulator.gameManager.getState(),r=DreamWide64.chunk(b,'RAM',2048),w=DreamWide64.chunk(b,'WRM',8192);return{paused:EJS_emulator.paused,fast:EJS_emulator.isFastForward,frame:EJS_emulator.gameManager.getFrameNum(),pauses:qaPauses.slice(-4),phase:[...b.slice(r+46,r+50)],command:b[r+0x31e],actor:b[r+0x30e],offset:b[r+0x32d],active:b[w+0x13c0],gate:b[w+0x13fd],mode:b[w+0x13fe],ready:b[w+0x13c1],batch:b[w+0x1372],rev:b[w+0x13b5],total:b[w+0x1398]+256*b[w+0x1399],remaining:DreamLargeBattle.decode(b)?.remaining,group:DreamGroupBlast.inspect(),shownCanvas:!!document.querySelector('#dbz-group-blast')&&!document.querySelector('#dbz-group-blast').hidden};};
 });
 await f.evaluate(id=>window.qaChosenID=id,Number(process.env.SKILL||34));console.log('LOADED',n);const before=await f.evaluate(()=>({read:qaRead(),view:DreamLargeBattle.decode(EJS_emulator.gameManager.getState())}));const allowed=new Set(before.view.enemies.map(e=>e.type));assert.equal(before.view.total,n,'fixture full count');
 console.log('BEFORE',JSON.stringify(before.read));const start=Date.now(),events=[];let previous='',ever=false;while(Date.now()-start<60000){const v=await f.evaluate(()=>{const v=qaRead(),d=document.querySelector('#dbz-skills'),a=document.querySelector('[data-lock-code="8"]');if(!v.group.busy&&!v.group.waiting&&v.group.shown.length===0){if(d&&!d.hidden){const skill=d.querySelector('[data-skill="'+qaChosenID+'"]');if(skill&&!skill.disabled){skill.click();window.qaCastChosen=true;}else [...d.querySelectorAll('button')].find(b=>b.textContent.trim().startsWith(DreamSkills.catalog.find(f=>f.moves.some(m=>m.id===qaChosenID)).name)&&b.textContent.includes('›'))?.click();}else if(a.getAttribute('aria-pressed')!=='true')a.click();if(!d||d.hidden){if(v.phase[2]===8&&performance.now()-(window.qaLastConfirm||0)>600){window.qaLastConfirm=performance.now();DreamInput.input('qa-target',0,8,1);setTimeout(()=>DreamInput.input('qa-target',0,8,0),80);}}}return v;});const key=JSON.stringify([v.phase,v.active,v.gate,v.mode,v.ready,v.command,v.actor,v.remaining,v.group.logs.length,v.group.shown.length,v.group.lastError]);if(key!==previous){events.push(v);previous=key;console.log('STATE',n,key);}if(v.group.shown.length)ever=true;if(v.group.lastError)throw Error(v.group.lastError);if(v.group.completed?.some(c=>c.cast===1))break;await page.waitForTimeout(50);}
 const data=await f.evaluate(()=>({draws:qaDraws,frames:qaFrames,final:qaRead()}));result={n,elapsedMs:Date.now()-start,before,events,final:data.final,draws:data.draws,errors};for(const [key,png]of Object.entries(data.frames))fs.writeFileSync(q+'/'+(process.env.RUN||'')+n+'-'+key+'.png',Buffer.from(png.split(',')[1],'base64'));await page.screenshot({path:q+'/'+(process.env.RUN||'')+n+'-final.png'});
 assert(ever,'cohorts started');assert(data.final.group.completed?.some(c=>c.cast===1),'first cast completed');assert.equal(errors.length,0);
 const shown=data.final.group.shown.filter(g=>g.cast===1),ids=shown.flatMap(g=>g.targets);const expected=before.view.enemies.filter(e=>e.alive).map(e=>(before.view.offset||0)+e.index).concat((before.view.reserve||[]).filter(e=>e.alive).map(e=>e.index));assert.deepEqual([...ids].sort((a,b)=>a-b),expected.sort((a,b)=>a-b));assert.equal(new Set(ids).size,expected.length);
 const seen=new Map();for(const d of data.draws.filter(d=>d.waiting||d.cast===1)){assert.equal(d.missing.length,0,'exact native artwork exists');assert(d.appearances.every(a=>a.type===a.nativeType&&allowed.has(a.type)&&a.type===(before.view.enemies[a.id]?.type??before.view.enemies[(a.id%100)%5]?.type)),'each body matches its actual encounter record');assert.equal(d.alpha,1);if(d.waiting)continue;const key=d.cohort.join(',');if(!seen.has(key))seen.set(key,[]);seen.get(key).push(d);assert.equal(d.bodies,d.progress===1?d.size-d.dead:d.size,'whole cohort remains until common completion');assert.equal(d.counter,d.before-(d.progress===1?d.dead:0),'one deduction at completion');if(d.stage==='hit')assert.equal(d.blasts,d.size);}
 for(const [key,frames]of seen){assert(frames.some(d=>d.stage==='hit'),'visible hit '+key);assert(frames.filter(d=>d.stage==='fall').length>=2,'at least two falling frames '+key);assert.equal(frames.at(-1).progress,1);}
 const complete=data.final.group.completed.find(c=>c.cast===1);assert.equal(complete.presented,complete.nativeRemaining,'actual native final count');assert(shown.every((g,i)=>g.size>=5&&g.size<=7||n<5||i===shown.length-1&&g.size<5));
 const frames=data.draws.filter(d=>!d.waiting&&d.cast===1),seconds=(frames.at(-1).time-frames[0].time)/1000;result.performance={seconds,groups:shown.length,groupsPerSecond:shown.length/seconds,remaining:complete.nativeRemaining,types:[...allowed]};console.log('PASS',JSON.stringify({n,...result.performance}));
}catch(e){if(!result)result={n,error:e.stack,errors};fs.writeFileSync(q+'/'+(process.env.RUN||'')+n+'-result.json',JSON.stringify(result,null,2));throw e;}finally{if(result)fs.writeFileSync(q+'/'+(process.env.RUN||'')+n+'-result.json',JSON.stringify(result,null,2));await context.close();}
}
}finally{await browser.close()}})();
