const fs=require('fs'),assert=require('assert/strict');const {chromium}=require('C:/Users/garet/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),r='D:/Codex 2/projects/NES-Wide64-HPBP169',ed=JSON.parse(fs.readFileSync(r+'/dbz-wide64-v17-edition.json')),old=JSON.parse(fs.readFileSync(r+'/dbz-wide64-v16-edition.json')),source=[...fs.readFileSync('D:/Codex 2/projects/NES-Blast188-QA/v16-normal-gohan.state')],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.BASE||'http://127.0.0.1:8176')+'/dbz-wide64-v17-play.html');
 await page.evaluate(async({bytes,id})=>{await new Promise((ok,no)=>{const r=indexedDB.open('nes-dream-library-v1',2);r.onsuccess=()=>{const d=r.result,t=d.transaction('states','readwrite');t.objectStore('states').put({key:id+':1',gameId:id,slot:1,bytes:new Uint8Array(bytes).buffer,updated:Date.now()});t.oncomplete=()=>{d.close();ok()};t.onerror=()=>no(t.error)}})},{bytes:source,id:old.romId});
 await page.locator('#wide64-v17-preview-notice').waitFor();await page.frameLocator('iframe').getByRole('button',{name:'Play game',exact:true}).click({timeout:60000});const f=page.frames().find(x=>x.url().includes('/player-wide64-v17.html'));await f.waitForFunction(()=>window.dreamArtwork?.metrics.frames>2,{},{timeout:60000});
 await page.waitForTimeout(500);await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByRole('button',{name:'Copy v16 save to v17',exact:true}).click();await page.getByRole('button',{name:'Copy selected save',exact:true}).click();await page.getByRole('button',{name:'Load copied v17 save',exact:true}).waitFor();await page.screenshot({path:__dirname+'/active-copy-confirmed.png'});await page.getByRole('button',{name:'Load copied v17 save',exact:true}).click();
 await f.waitForFunction(()=>DreamLargeBattle.decode(EJS_emulator.gameManager.getState())?.total===400);await page.waitForTimeout(300);
 await f.evaluate(()=>{window.orderRead=()=>{const b=EJS_emulator.gameManager.getState(),r=DreamWide64.chunk(b,'RAM',2048),w=DreamWide64.chunk(b,'WRM',8192);return {phase:[...b.slice(r+46,r+50)],actor:b[r+0x30e],offset:b[r+0x32d],work:[...b.slice(w+0x1e60,w+0x1e63)],party:Array.from({length:9},(_,i)=>{const a=r+0x200+i*18;return{id:b[a],status:b[a+15],packed:b[a+13],def:(b[a+14]>>4)===15?(b[w+0x1c81+i*18]||256):b[a+14]>>4}}),cards:DreamCards.inspect(),group:DreamGroupBlast.inspect()};};document.querySelector('[data-lock-code="8"]').click();});
 const events=[];let first=null;const start=Date.now();while(Date.now()-start<45000){await page.waitForTimeout(40);const v=await f.evaluate(()=>{const v=orderRead(),d=document.querySelector('#dbz-skills'),a=document.querySelector('[data-lock-code="8"]');if(d&&!d.hidden){const skill=d.querySelector('[data-skill="34"]');if(skill&&!skill.disabled)skill.click();else{const folder=[...d.querySelectorAll('button')].find(b=>b.textContent.includes('Frieza')&&!b.textContent.includes('soldiers'));folder?.click();}}return {phase:v.phase,actor:v.actor,offset:v.offset,work:v.work,party:v.party,groups:v.group.logs.length,completed:v.group.completed,detail:{busy:v.group.busy,waiting:v.group.waiting,animating:v.group.animating,error:v.group.lastError,queue:v.group.queued,presented:v.group.presented,last:v.group.logs.at(-1),lastShown:v.group.shown.at(-1)},native:(()=>{const b=EJS_emulator.gameManager.getState(),w=DreamWide64.chunk(b,'WRM',8192);return{active:b[w+0x13c0],gate:b[w+0x13fd],last:b[w+0x13ff],full:b[w+0x1398]+256*b[w+0x1399],remaining:DreamLargeBattle.decode(b)?.remaining,awake:DreamWide64Awakening.inspect()}})()};});if(JSON.stringify(v)!==JSON.stringify(events.at(-1))){events.push(v);if(v.groups>=78)console.log('ENDTRACE',JSON.stringify(v));}if(v.completed.length){first=v;break;}}
 fs.writeFileSync(__dirname+'/copy-end.state',Buffer.from(await f.evaluate(()=>[...EJS_emulator.gameManager.getState()])));await f.evaluate(()=>DreamTouch.releaseAll());await page.waitForTimeout(1200);await f.evaluate(()=>EJS_emulator.pause());await page.screenshot({path:__dirname+'/active-copy-running.png'});
 const original=await page.evaluate(async id=>new Promise((ok,no)=>{const r=indexedDB.open('nes-dream-library-v1',2);r.onsuccess=()=>{const d=r.result,t=d.transaction('states','readonly'),g=t.objectStore('states').get(id+':1');g.onsuccess=()=>ok([...new Uint8Array(g.result.bytes)]);t.oncomplete=()=>d.close();};r.onerror=()=>no(r.error)}),old.romId);assert.deepEqual(original,source);fs.writeFileSync(__dirname+'/active-copy-ui.json',JSON.stringify({first,events,sourcePreserved:true,errors},null,2));assert(first,'copied battle completed its all-target attack');assert.equal(first.completed[0].presented,first.completed[0].nativeRemaining);assert.equal(first.work[2],0,'party-origin actor');assert.equal(first.actor,first.party[first.offset/18].id);assert.equal(errors.length,0);console.log('PASS active battle copy completes groups',first.actor,first.offset);
}finally{await browser.close();}})();