const fs=require('fs'),assert=require('assert/strict');const{chromium}=require('C:/Users/garet/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const v=process.env.VERSION||'17',r='D:/Codex 2/projects/NES-Wide64-HPBP169',ed=JSON.parse(fs.readFileSync(r+`/dbz-wide64-v${v}-edition.json`)),fixture=process.env.FIXTURE||'D:/Codex 2/projects/NES-Blast189-QA/v17-100.state';
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});let f;const label=v+(process.env.CPU?'-cpu'+process.env.CPU:'');const result={version:v,errors:[],samples:[]};try{page.on('pageerror',e=>result.errors.push(e.message));await page.goto(`http://127.0.0.1:8176/dbz-wide64-v${v}-play.html`);await page.evaluate(async({bytes,id})=>{await new Promise((ok,no)=>{const x=indexedDB.open('nes-dream-library-v1',2);x.onsuccess=()=>{const db=x.result,t=db.transaction('states','readwrite');t.objectStore('states').put({key:id+':1',gameId:id,slot:1,bytes:new Uint8Array(bytes).buffer,updated:Date.now()});t.oncomplete=ok;t.onerror=no;};});},{bytes:[...fs.readFileSync(fixture)],id:ed.romId});await page.locator('#wide64-v17-preview-notice').waitFor();await page.frameLocator('iframe').getByRole('button',{name:'Play game',exact:true}).click({timeout:60000});f=page.frames().find(x=>x.url().includes(`/player-wide64-v${v}.html`));await f.waitForFunction(()=>window.dreamArtwork?.metrics.frames>2,{},{timeout:60000});await page.waitForTimeout(500);await page.evaluate(()=>document.querySelector('iframe').contentWindow.postMessage({channel:'nes-dream',type:'speed',value:1},location.origin));await page.waitForTimeout(60);await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByRole('button',{name:/Slot 1/}).click();await page.waitForTimeout(400);await page.evaluate(()=>document.querySelector('iframe').contentWindow.postMessage({channel:'nes-dream',type:'speed',value:1},location.origin));await f.evaluate(()=>DreamTouch.settings({a:2,b:6}));
await f.evaluate(()=>{window.skillTrace=[];window.qaDecode={count:0,ms:0};const decode=DreamLargeBattle.decode;DreamLargeBattle.decode=function(...args){const t=performance.now();try{return decode.apply(this,args)}finally{qaDecode.count++;qaDecode.ms+=performance.now()-t;}};const e=EJS_emulator;for(const name of ['play','pause']){const original=e[name];e[name]=function(...args){skillTrace.push({at:performance.now(),name,stack:Error().stack.split('\n').slice(2,5).join('\n')});return original.apply(this,args);};}window.readSkill=()=>{const b=e.gameManager.getState(),r=DreamWide64.chunk(b,'RAM',2048),w=DreamWide64.chunk(b,'WRM',8192);return{at:performance.now(),phase:b[r+0x30],slot:b[r+0x9a],frame:e.gameManager.getFrameNum(),paused:e.paused,pending:[...b.slice(w+0x1efc,w+0x1f00)],commands:Array.from({length:9},(_,i)=>b[r+0x210+i*18]),dialog:!document.querySelector('#dbz-skills').hidden,text:document.querySelector('.dbz-skill-notice').textContent};};});

const start=Date.now();while(Date.now()-start<30000){const st=await f.evaluate(()=>readSkill());if(st.dialog)break;if([6,7].includes(st.phase)){await f.evaluate(()=>DreamSkills.open());continue;}await f.evaluate(()=>{const a=document.querySelector('[data-lock-code="8"]');if(a.getAttribute('aria-pressed')!=='true')a.click();});await page.waitForTimeout(40);}
assert((await f.evaluate(()=>readSkill())).dialog,'skill page available');const baseline=await f.evaluate(()=>[...EJS_emulator.gameManager.getState()]);
result.moves=[];const catalog=await f.evaluate(()=>DreamSkills.catalog);const seen=new Set();
for(const folder of catalog){for(const move of folder.moves){if(move.id>=35||seen.has(move.id))continue;seen.add(move.id);
 await f.evaluate(({bytes,id})=>{DreamTouch.releaseAll();EJS_emulator.pause();DreamSkills.reset();DreamGroupBlast.reset();const gm=EJS_emulator.gameManager;gm.toggleFastForward(0);EJS_emulator.isFastForward=false;gm.FS.writeFile('/matrix.state',new Uint8Array(bytes));gm.functions.loadState('matrix.state',0);EJS_emulator.play();},{bytes:baseline,id:move.id});
 await page.waitForTimeout(100);await f.evaluate(()=>DreamSkills.open());await f.waitForFunction(()=>!document.querySelector('#dbz-skills').hidden,{},{timeout:8000});await f.getByRole('button',{name:folder.name+'  ›',exact:true}).click();const b=await f.evaluate(()=>readSkill());const began=Date.now();await f.locator('[data-skill="'+move.id+'"]').click();await f.waitForFunction(()=>document.querySelector('#dbz-skills').hidden||document.querySelector('.dbz-skill-notice').textContent.includes('retry')||document.querySelector('.dbz-skill-notice').textContent.includes('moved'),{},{timeout:12000});const a=await f.evaluate(()=>readSkill());const chosen={id:move.id,name:move.name,ms:Date.now()-began,slot:b.slot,command:a.commands[b.slot/18],phase:a.phase,closed:!a.dialog,notice:a.text};result.moves.push(chosen);console.log(JSON.stringify(chosen));assert(chosen.closed,move.name+' closes');assert.equal(chosen.command,192+move.id,move.name+' native command');
 }}assert.equal(result.moves.length,35);assert.equal(result.errors.length,0);await page.screenshot({path:__dirname+'/skills-matrix-final.png'});console.log('PASS all35skills');
}finally{fs.writeFileSync(__dirname+'/skills-matrix.json',JSON.stringify(result,null,2));await browser.close();}})();
