const fs=require('fs'),assert=require('assert/strict');const {chromium}=require('C:/Users/garet/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
const page=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true}),errors=[],http=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)http.push([r.status(),r.url()])});const build=JSON.parse(fs.readFileSync('D:/Codex 2/projects/NES-Pad181-QA/build.json'));const base=process.env.BASE||'http://127.0.0.1:8176';
await page.goto(base+'/dbz-wide64-v16-play.html');
await page.evaluate(async({bytes,id})=>{await new Promise((ok,no)=>{const r=indexedDB.open('nes-dream-library-v1',2);r.onsuccess=()=>{const d=r.result,t=d.transaction('states','readwrite');t.objectStore('states').put({key:id+':1',gameId:id,slot:1,bytes:new Uint8Array(bytes).buffer,updated:Date.now()});t.oncomplete=()=>{d.close();ok()};t.onerror=()=>no(t.error)};r.onerror=()=>no(r.error)})},{bytes:[...fs.readFileSync(__dirname+'/v16-normal-gohan.state')],id:'ed0e63256c9b6cb182db23f267812c97ffc14e4c5c76730bcd96676c7feed6da'});
await page.frameLocator('iframe').getByRole('button',{name:'Play game',exact:true}).click({timeout:60000});const f=page.frames().find(x=>x.url().includes('/player-wide64-v16.html'));await f.waitForFunction(()=>window.dreamArtwork?.metrics.frames>2,{},{timeout:60000});await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByRole('button',{name:/Slot 1/}).click();await f.waitForFunction(()=>DreamLargeBattle.decode(EJS_emulator.gameManager.getState())?.remaining>=0,{},{timeout:30000});await page.waitForTimeout(800);await f.evaluate(()=>EJS_emulator.pause());
const result=await f.evaluate(()=>({title:document.title,release:document.body.dataset.wide64Release,path:document.querySelector('.pad-outline path').getAttribute('d'),remaining:DreamLargeBattle.decode(EJS_emulator.gameManager.getState())?.remaining,rom:DreamWide64.ROM}));assert.equal(result.release,'188');assert.equal(result.path,build.restoredPath);assert.equal(result.rom,'ed0e63256c9b6cb182db23f267812c97ffc14e4c5c76730bcd96676c7feed6da');assert(Number.isInteger(result.remaining));assert(await page.locator('[data-verified="true"]').count());
const directions=await f.evaluate(()=>{const pad=document.querySelector('#direction-pad'),b=pad.getBoundingClientRect(),original=DreamInput.input,held=new Set(),events=[];DreamInput.input=(source,player,code,val)=>{if(val)held.add(code);else held.delete(code)};const fire=(type,x,y)=>pad.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:181,pointerType:'touch',buttons:type==='pointerup'?0:1,clientX:b.x+b.width*x,clientY:b.y+b.height*y}));try{for(const [x,y,want]of [[.5,.1,[4]],[.9,.1,[4,7]],[.9,.5,[7]],[.9,.9,[5,7]],[.5,.9,[5]],[.1,.9,[5,6]],[.1,.5,[6]],[.1,.1,[4,6]]]){fire('pointerdown',x,y);events.push({want,actual:[...held].sort()});fire('pointerup',x,y);if(held.size)throw Error('Stuck input');}fire('pointerdown',.5,.1);fire('pointermove',.9,.5);events.push({want:[7],actual:[...held].sort()});fire('pointercancel',.9,.5);if(held.size)throw Error('Stuck cancel');return events}finally{DreamTouch.releaseAll();DreamInput.input=original;}});for(const t of directions)assert.deepEqual(t.actual,t.want);
await page.screenshot({path:__dirname+'/phone188.png'});await f.locator('#direction-pad').screenshot({path:__dirname+'/dpad188.png'});await page.setViewportSize({width:844,height:390});await page.waitForTimeout(300);await page.screenshot({path:__dirname+'/landscape188.png'});assert.equal(errors.length,0);assert.equal(http.length,0);fs.writeFileSync(__dirname+'/controls-qa.json',JSON.stringify({base,result,directions,errors,http},null,2));console.log(JSON.stringify({base,result,directions:directions.length,errors,http}));
}finally{await browser.close()}})();

