const fs=require('fs'),assert=require('assert/strict');const {chromium}=require('C:/Users/garet/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),r='D:/Codex 2/projects/NES-Wide64-HPBP169',ed=JSON.parse(fs.readFileSync(r+'/dbz-wide64-v16-edition.json')),old=JSON.parse(fs.readFileSync(r+'/dbz-wide64-v16-edition.json')),source=[...fs.readFileSync('D:/Codex 2/projects/NES-Blast188-QA/v16-order-menu.state')],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({id})=>localStorage.setItem('nes-dream:dbz-crazy-cards:'+id,JSON.stringify({cards:[256,255,64,16,8].map(defense=>({attack:256,defense,attribute:1,locked:true}))})),{id:ed.romId});
 await page.addInitScript(()=>{window.qaStarted=false;addEventListener('message',e=>{if(e.data?.channel==='nes-dream'&&e.data?.type==='started')window.qaStarted=true;});});
 await page.goto((process.env.BASE||'http://127.0.0.1:8176')+'/dbz-wide64-v16-play.html');
 await page.evaluate(async({bytes,id})=>{await new Promise((ok,no)=>{const r=indexedDB.open('nes-dream-library-v1',2);r.onsuccess=()=>{const d=r.result,t=d.transaction('states','readwrite');t.objectStore('states').put({key:id+':1',gameId:id,slot:1,bytes:new Uint8Array(bytes).buffer,updated:Date.now()});t.oncomplete=()=>{d.close();ok()};t.onerror=()=>no(t.error)}})},{bytes:source,id:old.romId});
 await page.frameLocator('iframe').getByRole('button',{name:'Play game',exact:true}).click({timeout:60000});const f=page.frames().find(x=>x.url().includes('/player-wide64-v16.html'));await f.waitForFunction(()=>window.dreamArtwork?.metrics.frames>2);
 await page.waitForFunction(()=>window.qaStarted,{},{timeout:60000});
 await page.evaluate(()=>document.querySelector('iframe').contentWindow.postMessage({channel:'nes-dream',type:'speed',value:1},location.origin));await f.evaluate(()=>DreamTouch.settings({a:4,b:6}));await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByRole('button',{name:/Slot 1/}).click();
 await f.waitForFunction(()=>DreamLargeBattle.decode(EJS_emulator.gameManager.getState())?.total===400);await page.waitForTimeout(300);
 await f.evaluate(()=>{window.orderRead=()=>{const b=EJS_emulator.gameManager.getState(),r=DreamWide64.chunk(b,'RAM',2048),w=DreamWide64.chunk(b,'WRM',8192);return {phase:[...b.slice(r+46,r+50)],actor:b[r+0x30e],offset:b[r+0x32d],work:[...b.slice(w+0x1e60,w+0x1e63)],party:Array.from({length:9},(_,i)=>{const a=r+0x200+i*18;return{id:b[a],status:b[a+15],packed:b[a+13],def:(b[a+14]>>4)===15?(b[w+0x1c81+i*18]||256):b[a+14]>>4}}),cards:DreamCards.inspect(),group:DreamGroupBlast.inspect()};};document.querySelector('[data-lock-code="8"]').click();});
 const events=[];let first=null;const start=Date.now();while(Date.now()-start<60000){await page.waitForTimeout(40);const v=await f.evaluate(()=>{const v=orderRead(),d=document.querySelector('#dbz-skills'),a=document.querySelector('[data-lock-code="8"]');if(!DreamWide64Awakening.isOpen()&&!v.group.busy&&(d?.hidden!==false)&&a.getAttribute('aria-pressed')!=='true')a.click();if(d&&!d.hidden){const skill=d.querySelector('[data-skill="34"]');if(skill&&!skill.disabled)skill.click();else{const folder=[...d.querySelectorAll('button')].find(b=>b.textContent.includes('Frieza')&&!b.textContent.includes('soldiers'));folder?.click();}}return {phase:v.phase,actor:v.actor,offset:v.offset,work:v.work,party:v.party};});if(JSON.stringify(v)!==JSON.stringify(events.at(-1)))events.push(v);if(v.phase[0]===1&&v.phase[2]>=34&&v.phase[2]<=39&&v.party[v.offset/18]?.status===31){first=v;break;}}
 await f.evaluate(()=>{DreamTouch.releaseAll();EJS_emulator.pause();});await page.screenshot({path:__dirname+'/live-highest-def-first.png'});
 const original=await page.evaluate(async id=>new Promise((ok,no)=>{const r=indexedDB.open('nes-dream-library-v1',2);r.onsuccess=()=>{const d=r.result,t=d.transaction('states','readonly'),g=t.objectStore('states').get(id+':1');g.onsuccess=()=>ok([...new Uint8Array(g.result.bytes)]);t.oncomplete=()=>d.close();};r.onerror=()=>no(r.error)}),old.romId);assert.deepEqual(original,source);fs.writeFileSync(__dirname+'/live-order-ui.json',JSON.stringify({first,events,sourcePreserved:true,errors},null,2));assert(first,'native first attack reached');assert.equal(first.work[2],0,'party-origin actor');assert.equal(first.work[1],0,'highest DEF256 selected');assert.equal(first.actor,first.party[first.offset/18].id);assert.equal(errors.length,0);console.log('PASS actual copied-save battle first actor DEF256',first.actor,first.offset);
}finally{await browser.close();}})();

