const fs=require('fs'),assert=require('assert/strict');const {chromium}=require('C:/Users/garet/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/Codex 2/projects/NES-Wide64-HPBP169',edition=JSON.parse(fs.readFileSync(root+'/dbz-wide64-v16-edition.json'));
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,recordVideo:{dir:__dirname+'/video',size:{width:390,height:844}}});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('error',e.message)});
page.on('console',m=>{if(m.text().startsWith('battle182'))console.log(m.text());});
await page.goto((process.env.BASE||'http://127.0.0.1:8176')+'/dbz-wide64-v16-play.html');
await page.evaluate(async({bytes,id})=>{await new Promise((ok,no)=>{const q=indexedDB.open('nes-dream-library-v1',2);q.onsuccess=()=>{const d=q.result,t=d.transaction('states','readwrite');t.objectStore('states').put({key:id+':1',gameId:id,slot:1,bytes:new Uint8Array(bytes).buffer,updated:Date.now()});t.oncomplete=()=>{d.close();ok();};t.onerror=()=>no(t.error);};q.onerror=()=>no(q.error);});},{bytes:[...fs.readFileSync(process.env.FIXTURE||__dirname+'/v16-ordinary.state')],id:edition.romId});
await page.frameLocator('iframe').getByRole('button',{name:'Play game',exact:true}).click({timeout:60000});const f=page.frames().find(f=>f.url().includes('/player-wide64-v16.html'));await f.waitForFunction(()=>window.dreamArtwork?.metrics?.frames>2,{},{timeout:60000});
await page.getByRole('button',{name:'Load',exact:true}).click();await page.getByRole('button',{name:/Slot 1/}).click();await page.waitForTimeout(600);await page.evaluate(()=>document.querySelector('iframe').contentWindow.postMessage({channel:'nes-dream',type:'speed',value:256},location.origin));
await page.screenshot({path:__dirname+'/ui-loaded.png'});

await f.evaluate(()=>{window.qaDraws=[];window.qaCaptures={};const original=DreamGroupBlastVisual.draw;DreamGroupBlastVisual.draw=(ctx,w,h,scene)=>{const fill=ctx.fillText,draw=ctx.drawImage;let text='',paintedBodies=0,paintedBlasts=0;ctx.drawImage=function(im,...args){if(im.src?.includes('/enemies/body-type-'))paintedBodies++;if(/impact[12]\.png/.test(im.src||''))paintedBlasts++;return draw.call(this,im,...args);};ctx.fillText=function(t,...args){if(String(t).includes('ENEMIES'))text=t;return fill.call(this,t,...args)};try{original(ctx,w,h,scene)}finally{ctx.fillText=fill;ctx.drawImage=draw;}{const entry={time:performance.now(),text,waiting:!!scene.waiting,paintedBodies,paintedBlasts,rendered:DreamGroupBlastVisual.inspect().lastDraw,progress:scene.progress,size:scene.enemies.length,before:scene.remainingBefore,dead:scene.enemies.filter(e=>e.beforeHp>0&&e.afterHp===0).length,ids:scene.enemies.map(e=>e.id),types:scene.enemies.map(e=>e.type)};qaDraws.push(entry);const key=scene.enemies.length+'-'+(scene.waiting?'preview':scene.progress===1?'gone':scene.progress===0?'appear':scene.progress>.65?'fall':scene.progress>=.12&&scene.progress<.48?'hit':'moving');if(!qaCaptures[key])qaCaptures[key]=ctx.canvas.toDataURL();}};});
await f.evaluate(()=>{const g=EJS_emulator.gameManager;window.qaRead180=()=>{const b=g.getState(),r=DreamWide64.chunk(b,'RAM',2048),w=DreamWide64.chunk(b,'WRM',8192);return {phase:[...b.slice(r+46,r+50)],kills:[b[w+0x13bb],b[w+0x13bc]],forms:b[w+0x15ae],queue:b[w+0x13be],loaded:b[w+0x139a]+256*b[w+0x139b],pending:b[w+0x1396]+256*b[w+0x1397],frame:g.getFrameNum(),page:b[w+0x1370],active:b[w+0x13c0],remaining:DreamLargeBattle.decode(b)?.remaining,bp:b[r+0x31e],banner:DreamWide64Awakening.inspect()};};document.querySelector('[data-lock-code="8"]').click();});


const start=Date.now(),samples=[];while(Date.now()-start<25000){await page.waitForTimeout(100);samples.push(await f.evaluate(()=>{const v=qaRead180(),d=document.querySelector('#dbz-skills');if(d&&!d.hidden){const skill=d.querySelector('[data-skill="0"]');if(skill&&!skill.disabled)skill.click();else [...d.querySelectorAll("button")].find(b=>b.textContent.includes("Goku")&&b.textContent.includes("›"))?.click();}return {...v,group:DreamGroupBlast.inspect(),covered:DreamGroupBlast.coversScreen()};}));}
await f.evaluate(()=>{DreamTouch.releaseAll();EJS_emulator.pause();});await page.screenshot({path:__dirname+'/single-target.png'});fs.writeFileSync(__dirname+'/single-target.json',JSON.stringify({samples,errors},null,2));assert(samples.some(s=>s.phase[2]>=34||s.remaining<400),'native attack executes or has completed');assert(samples.every(s=>!s.covered&&s.group.logs.length===0),'single target never opens a group');assert(samples.some(s=>s.remaining<400),'ordinary attack updates actual survivor count');assert.equal(errors.length,0);console.log('PASS single target',Math.min(...samples.map(s=>s.remaining)));await browser.close();})();
