import {W,H,VERSION,types,objects,layoutObjects,validFound,collect,counts,localPoint,clampCamera} from './scene-v3.js';
import {Sounds} from './sound.js';
const $=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d',{alpha:false}),viewport=$('viewport'),key='little-finds-harbour-v'+VERSION;
let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{}
let found=validFound(saved.found),misses=Number.isFinite(saved.misses)?Math.max(0,saved.misses):0,hints=Number.isFinite(saved.hints)?Math.max(0,saved.hints):0;
const sounds=new Sounds(saved.sound!==false),images={},masks={},flights=[],reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let metadata,placed=[],ready=false,cw=0,ch=0,dpr=1,cam={s:1,x:0,y:0},fit=1,maxScale=3,scheduled=false,toastTimer,hintUntil=0,hintId=null,lastHint=0,selected=null;
let saveTimer;function save(){clearTimeout(saveTimer);saveTimer=setTimeout(persist,220);}function persist(){try{localStorage.setItem(key,JSON.stringify({found:[...found],misses,hints,sound:sounds.enabled,view:{...cam}}));}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>($('toast').classList.remove('show'),$('toast').textContent='Drag to explore · pinch to zoom · find every copy'),1600);}
function updateSound(){$('sound').textContent=sounds.enabled?'♪ Sound on':'♪ Sound off';$('sound').setAttribute('aria-label',sounds.enabled?'Sound on':'Sound off');$('sound').setAttribute('aria-pressed',String(sounds.enabled));}
function thumb(type){const box=document.createElement('div');box.className='thumb';const im=document.createElement('img');im.src=`assets-v3/${type}.webp`;im.alt=types[type];const m=metadata[type],b=m.bounds,bw=b[2]-b[0],bh=b[3]-b[1];const ratio=bw/bh;const h=ratio>1.4?72/ratio:48,w=h*ratio;im.style.width=`${m.size[0]/bw*w}px`;im.style.height=`${m.size[1]/bh*h}px`;im.style.left=`calc(50% - ${w/2+b[0]/bw*w}px)`;im.style.top=`calc(50% - ${h/2+b[1]/bh*h}px)`;box.append(im);return box;}
function makeCard(type,all=false){const c=counts(found,type),card=document.createElement('button');card.className='card'+(c.found===c.total?' done':'');card.dataset.type=type;card.setAttribute('aria-label',`${types[type]}: ${c.found} of ${c.total} found`);const name=document.createElement('span');name.className='label';name.textContent=types[type];const n=document.createElement('span');n.className='amount';n.textContent=`${c.found} / ${c.total}`;card.append(thumb(type),name,n);card.onclick=()=>{selected=type;if(all)$('groups').close();toast(c.found===c.total?'You found this whole group!':`Look for ${c.total-c.found} more ${types[type].toLowerCase()}`);};return card;}
function update(){const n=found.size;$('count').textContent=`${n} / 50`;$('bar').style.width=n*2+'%';$('traytitle').textContent=n===50?'Every treasure found!':'Find these little treasures';if(!metadata)return;const incomplete=Object.keys(types).filter(t=>counts(found,t).found<counts(found,t).total);$('tray').replaceChildren(...(incomplete.length?incomplete:Object.keys(types)).slice(0,4).map(t=>makeCard(t)));$('collection').replaceChildren(...Object.keys(types).map(t=>makeCard(t,true)));}
function resize(){const r=viewport.getBoundingClientRect(),old={...cam},ow=cw,oh=ch;cw=r.width;ch=r.height;dpr=Math.min(devicePixelRatio||1,2,Math.sqrt(3000000/(cw*ch)));canvas.width=Math.round(cw*dpr);canvas.height=Math.round(ch*dpr);fit=Math.min(cw/W,ch/H);maxScale=Math.max(fit*5,1.8);if(ow){const centre={x:(ow/2-old.x)/old.s,y:(oh/2-old.y)/old.s};cam.s=Math.max(fit,Math.min(maxScale,old.s));cam.x=cw/2-centre.x*cam.s;cam.y=ch/2-centre.y*cam.s;}else{cam.s=Math.max(fit,Math.min(ch/H,cw/W*2.5));cam.x=(cw-W*cam.s)/2;cam.y=(ch-H*cam.s)/2;if(saved.view&&Number.isFinite(saved.view.s)&&Number.isFinite(saved.view.x)&&Number.isFinite(saved.view.y)){cam={s:Math.max(fit,Math.min(maxScale,saved.view.s)),x:saved.view.x,y:saved.view.y};}}clampCamera(cam,cw,ch);requestDraw();}
function requestDraw(){if(!scheduled){scheduled=true;requestAnimationFrame(draw);}}
function drawSprite(o,scale=1,alpha=1,lift=0){ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2-lift);ctx.scale(scale,scale);ctx.globalAlpha=alpha;ctx.drawImage(images[o.type],-o.w/2,-o.h/2,o.w,o.h);ctx.restore();}
function foreground(){ctx.save();ctx.beginPath();ctx.moveTo(1023,704);ctx.lineTo(1039,704);ctx.lineTo(1013,861);ctx.lineTo(996,859);ctx.closePath();ctx.clip();ctx.drawImage(images.master,0,0,W,H);ctx.restore();}
function draw(now){scheduled=false;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#e5e5cd';ctx.fillRect(0,0,cw,ch);if(!ready)return;ctx.save();ctx.translate(cam.x,cam.y);ctx.scale(cam.s,cam.s);ctx.drawImage(images.background,0,0,W,H);for(const o of placed)if(!found.has(o.id))drawSprite(o);if(hintId&&now<hintUntil){const o=placed.find(v=>v.id===hintId);if(o&&!found.has(o.id)){ctx.save();ctx.strokeStyle='#fff0a2';ctx.lineWidth=3/cam.s;ctx.setLineDash([7/cam.s,5/cam.s]);ctx.strokeRect(o.x-8,o.y-8,o.w+16,o.h+16);ctx.restore();}}else hintId=null;
foreground();for(let i=flights.length-1;i>=0;i--){const f=flights[i],t=Math.min(1,(now-f.start)/(reduced?160:650));if(t>=1){flights.splice(i,1);continue;}const s=reduced?1:1+Math.sin(t*Math.PI)*.32;drawSprite(f.o,s,1-t*t,reduced?0:40*t/cam.s);}ctx.restore();if(flights.length||hintId)requestDraw();}
function maskHit(o,x,y){if(o.type==='tabby'&&y>=704&&y<=861){const edge=1023-(y-704)*27/157;if(x>=edge&&x<=edge+17)return false;}const p=localPoint(o,x,y);if(p.x<0||p.x>1||p.y<0||p.y>1)return false;const m=masks[o.type];return m.data[(Math.min(95,Math.floor(p.y*96))*96+Math.min(95,Math.floor(p.x*96)))*4+3]>130;}
function pick(x,y){if(!ready)return;const wx=(x-cam.x)/cam.s,wy=(y-cam.y)/cam.s;const o=[...placed].reverse().find(o=>!found.has(o.id)&&maskHit(o,wx,wy));if(!o){misses++;sounds.play('wrong');toast(['Oops—try a little treasure!','Boop! Not this one.','The bakery is keeping its secrets!'][misses%3]);save();return;}
if(!collect(found,o.id))return;flights.push({o,start:performance.now()});const c=counts(found,o.type),complete=c.found===c.total;sounds.play(found.size===50?'win':complete?'group':o.type==='duck'?'duck':'correct');toast(complete?`${types[o.type]} · all found!`:`${types[o.type]} · ${c.found} / ${c.total}`);save();update();requestDraw();if(found.size===50){setTimeout(()=>{if(found.size===50){$('win-stats').textContent=`50 finds · ${hints} hints used`;$('win').showModal();}},750);}}
function zoom(factor,x=cw/2,y=ch/2){const s=Math.max(fit,Math.min(maxScale,cam.s*factor)),wx=(x-cam.x)/cam.s,wy=(y-cam.y)/cam.s;cam.s=s;cam.x=x-wx*s;cam.y=y-wy*s;clampCamera(cam,cw,ch);requestDraw();save();}
function move(dx,dy=0){cam.x+=dx;cam.y+=dy;clampCamera(cam,cw,ch);requestDraw();save();}
const pointers=new Map();let gesture=null;
function pos(e){const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
canvas.addEventListener('pointerdown',e=>{sounds.unlock();canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,pos(e));if(pointers.size===1)gesture={start:pos(e),last:pos(e),moved:false,pinched:false};else if(gesture)gesture.pinched=true;});
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;const before=[...pointers.values()];pointers.set(e.pointerId,pos(e));const after=[...pointers.values()];if(after.length>=2){const bmid={x:(before[0].x+before[1].x)/2,y:(before[0].y+before[1].y)/2},mid={x:(after[0].x+after[1].x)/2,y:(after[0].y+after[1].y)/2},d0=Math.hypot(before[1].x-before[0].x,before[1].y-before[0].y),d1=Math.hypot(after[1].x-after[0].x,after[1].y-after[0].y);if(d0>8)zoom(d1/d0,bmid.x,bmid.y);move(mid.x-bmid.x,mid.y-bmid.y);gesture.pinched=true;}else{const p=pos(e);if(Math.hypot(p.x-gesture.start.x,p.y-gesture.start.y)>7)gesture.moved=true;if(gesture.moved||gesture.pinched)move(p.x-gesture.last.x,p.y-gesture.last.y);gesture.last=p;}});
canvas.addEventListener('pointerup',e=>{if(!pointers.has(e.pointerId))return;const p=pos(e),tap=pointers.size===1&&gesture&&!gesture.moved&&!gesture.pinched;pointers.delete(e.pointerId);if(tap)pick(p.x,p.y);if(pointers.size){gesture.last=[...pointers.values()][0];gesture.pinched=true;}else gesture=null;save();});
function cancel(e){pointers.delete(e.pointerId);if(!pointers.size)gesture=null;}
canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('lostpointercapture',cancel);
canvas.addEventListener('wheel',e=>{e.preventDefault();const p=pos(e);zoom(Math.exp(-e.deltaY*.0015),p.x,p.y);},{passive:false});
canvas.addEventListener('keydown',e=>{const moves={ArrowLeft:[cw*.2,0],ArrowRight:[-cw*.2,0],ArrowUp:[0,ch*.2],ArrowDown:[0,-ch*.2]};if(moves[e.key]){e.preventDefault();move(...moves[e.key]);}else if(e.key==='+'||e.key==='=')zoom(1.3);else if(e.key==='-')zoom(1/1.3);});
$('plus').onclick=()=>zoom(1.35);$('minus').onclick=()=>zoom(1/1.35);$('fit').onclick=()=>{cam={s:fit,x:(cw-W*fit)/2,y:(ch-H*fit)/2};requestDraw();save();};$('sound').onclick=()=>{sounds.set(!sounds.enabled);updateSound();save();if(sounds.enabled)sounds.play('correct');};
$('hint').onclick=()=>{if(!ready||found.size===50)return;const now=performance.now();if(now-lastHint<12000&&lastHint){toast('Another hint will be ready in a moment.');return;}const target=placed.find(o=>!found.has(o.id)&&o.type===selected)||placed.find(o=>!found.has(o.id));lastHint=now;hints++;cam.s=Math.max(cam.s,Math.min(1.25,maxScale));cam.x=cw/2-(target.x+target.w/2)*cam.s;cam.y=ch/2-(target.y+target.h/2)*cam.s;clampCamera(cam,cw,ch);hintId=target.id;hintUntil=now+2400;requestDraw();save();toast('A little nudge ✦');};
$('menu').onclick=()=>$('options').showModal();$('resume').onclick=()=>$('options').close();$('all').onclick=()=>$('groups').showModal();$('close-groups').onclick=()=>$('groups').close();
$('test-sound').onclick=()=>{sounds.set(true);updateSound();save();sounds.play('correct');setTimeout(()=>sounds.play('wrong'),500);setTimeout(()=>sounds.play('group'),950);};
function restart(){found.clear();misses=0;hints=0;lastHint=0;hintId=null;flights.length=0;cam.s=Math.max(fit,Math.min(ch/H,cw/W*2.5));cam.x=(cw-W*cam.s)/2;cam.y=(ch-H*cam.s)/2;save();update();requestDraw();for(const id of ['win','options'])$(id).close();toast('A fresh little adventure!');}
$('restart').onclick=()=>{if($('restart').dataset.confirm==='yes'){restart();$('restart').textContent='Start this level again';delete $('restart').dataset.confirm;}else{$('restart').dataset.confirm='yes';$('restart').textContent='Reset all finds? Tap again';}};
$('again').onclick=restart;$('admire').onclick=()=>$('win').close();
document.addEventListener('visibilitychange',()=>{if(document.hidden){pointers.clear();gesture=null;persist();}else requestDraw();});
addEventListener('pagehide',persist);updateSound();update();new ResizeObserver(resize).observe(viewport);
async function load(){try{const response=await fetch('assets-v3/metadata.json');if(!response.ok)throw Error('Asset list unavailable');metadata=await response.json();let loaded=0;await Promise.all(['background','master',...Object.keys(types)].map(async id=>{const im=new Image();im.src=`assets-v3/${id}.webp`;await im.decode();images[id]=im;$('loadcount').textContent=`${++loaded} / 34 illustrations`;if(id!=='background'&&id!=='master'){const b=metadata[id].bounds,c=document.createElement('canvas');c.width=c.height=96;const cctx=c.getContext('2d',{willReadFrequently:true});cctx.drawImage(im,b[0],b[1],b[2]-b[0],b[3]-b[1],0,0,96,96);masks[id]=cctx.getImageData(0,0,96,96);}}));placed=layoutObjects(metadata);ready=true;$('loading').hidden=true;update();requestDraw();}catch(error){console.error(error);$('loadcount').textContent='Some artwork could not load. Tap below to retry.';const retry=document.createElement('button');retry.textContent='Retry loading';retry.onclick=()=>location.reload();$('loading').append(retry);}}
load();
